### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'Void RestSharp.RestClient..ctor(System.String)'.'

### ISSUE THREAD

**Issue by talley** [Dev-Owl/pillowsharp#5]
I got this error below when opening connection.
System.MissingMethodException: 'Method not found: 'Void RestSharp.RestClient..ctor(System.String)'.'

            var client = new PillowClient(new BasicCouchDBServer("http://127.0.0.1:5984", new CouchLoginData("admin", "party!"), ELoginTypes.TokenLogin)); //ERROR OCCURRED HERE

**Comment by Dev-Owl** [comment]
I know this is dated, but I'm working on the client and the new 4.X version is based on recent Rest sharp and will get more features. Closing this for now
